openapi: 3.0.1
info:
  title: API BS UTP Parking Request V1
  description: 'Permite registrar las solicitudes de usuarios para contar con el beneficio de usar los estacionamientos de la UTP.'
  version: 1.0.0
servers:
  - url: /utp-parking/v1
externalDocs:
  url: 'https://github.com/utp-parking-proyect'
  description: Organización de Github
tags:
  - name: Request Controller
    description: Parking request data controller
paths:
  /request:
    post:
      operationId: createParkingRequest
      summary: Registra solicitudes de ingreso a estacionamiento de la UTP.
      description: |-
        ### Acerca de la funcionalidad expuesta
        Esta API recibe la solicitud para la creación de una solicitud de ingreso al estacionamiento, enviadas por los canales web y móvil.

        ### Data de Prueba
        No aplica.
      tags:
        - Request Controller
      parameters:
        - $ref: '#/components/parameters/Request-ID'
        - $ref: '#/components/parameters/request-date'
        - $ref: '#/components/parameters/app-code'
        - $ref: '#/components/parameters/caller-name'
      requestBody:
        description: Entrada del Servicio.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParkingRequest'
        required: true
      responses:
        '201':
          description: Proceso de Registro Satisfactorio.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingRequestResponse'
        '400':
          description: Los datos proporcionados no son válidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '401':
          description: No está autorizado para consumir el API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '403':
          description: No tiene los permisos necesarios para ejecutar esta operacion.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '404':
          description: El recurso solicitado no fue encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '409':
          description: Los datos proporcionados no son válidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '500':
          description: Ocurrió un error inesperado. Por favor contactarse con Soporte T&eacute;cnico.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '503':
          description: El servicio no se encuentra disponible. Por favor reintente más tarde.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        '504':
          description: Se superó el tiempo de respuesta interna.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
components:
  schemas:
    ParkingRequest:
      type: object
      properties:
        idApplicant:
          type: integer
          description: ID del alumno.
          example: 1
        vehicleType:
          type: integer
          description: Tipo del vehículo.
          example: 1
        numberPlate:
          type: string
          description: Placa del vehículo.
          example: HNC-234
        isNew:
          type: boolean
          description: Validación si el vehículo es nuevo o no
          example: true
    ParkingRequestResponse:
      type: object
      properties:
        parkingRequestId:
          type: integer
          description: Identificador de la solicitud
          example: 1
    ApiException:
      title: ApiException
      type: object
      properties:
        description:
          type: string
          description: Descripcion del error de Sistema
          example: Error al llamar al servicio
        errorType:
          type: string
          description: Tipo de Error de Sistema
          example: TECHNICAL
        exceptionDetails:
          type: array
          description: Lista de detalles del error
          items:
            $ref: '#/components/schemas/ApiExceptionDetail'
        properties:
          type: object
          properties: {}
          description: Lista de propiedades especiales.
      description: Datos del error de sistema.
    ApiExceptionDetail:
      title: ApiExceptionDetail
      type: object
      properties:
        component:
          type: string
          description: Nombre del componente de falla
          example: business-parking-request
        description:
          type: string
          description: Descripcion del Detalle
          example: Date is not within the valid range for any cycle
      description: Datos del error técnico.
  parameters:
    Request-ID:
      name: Request-ID
      in: header
      description: Este campo es un valor estandar ya existente y sera usado como identificador.
      required: true
      schema:
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[34][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        type: string
        example: 550e8400-e29b-41d4-a716-446655440000
    request-date:
      name: request-date
      in: header
      description: Fecha de la petición
      required: true
      schema:
        maxLength: 29
        pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{4}([a-z]|[A-Z]|\d)?$'
        type: string
        example: '2020-10-09T14:02:03.987-0700'
    app-code:
      name: app-code
      in: header
      description: 'Codigo de la aplicacion que invoca el servicio. Se debe usar el codigo de 2 caracteres que tienen asignada las aplicaciones, puede ser el canal.'
      required: true
      schema:
        maxLength: 2
        minLength: 2
        pattern: '^[0-9A-Z]*$'
        type: string
        example: P0
    caller-name:
      name: caller-name
      in: header
      description: Nombre de la API que realiza la invocacion al servicio.
      required: true
      schema:
        maxLength: 100
        minLength: 5
        pattern: '^[0-9a-zA-Z.-]*$'
        type: string
        example: atlas-cross-services-loans-deposits-loan-loans-v2
  securitySchemes:
    bearerAuth:
      type: http
      description: 'Token de Authorización, header Authorization, ejemplo: Bearer 363536363jjxnj63633611'
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []